import { User, ShoppingCart, Heart, Search } from 'lucide-react'
import { JSX } from 'react'
export type ProductType= {
  id: string
  image: string[]
  SKU: string
  title: string
  price: number
  wishlist: boolean
  cart: boolean
  desc: string
  quantity: number
  stock: number
  size: string
  sizeOptions:string[]
  color: string
  colorOptions:string[]
  rating: number
  reviews: number
  category: string
  tags: string[]
} 
export type blogType = {
  id: string
  title: string
  image: string
  time: string
  date: string
  desc: string
  tag: string
  author: string
}
export type Link={
  pathname: string
  pathLink: string
}
export type IconLink= Link & {
  icon: JSX.Element
}
const Product:ProductType[] = [
  {
    id: 'af73b2d9',
    image: ['/product1.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'TRNTN-MD-4876',
    title: 'Trenton Modular Sofa_3',
    price: 799,
    wishlist: false,
    cart: false,
    desc: 'A stylish and versatile modular sofa designed for comfort and modern living. Perfect for customizing your space.',
    quantity: 1,
    stock: 5,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#8B4513', '#C0C0C0', '#F5F5DC'],
    rating: 4,
    reviews: 12,
    category: 'furniture',
    tags: ['sofa', 'furniture', 'modular'],
  },
  {
    id: 'd3f6a89c',
    image: ['/product2.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'GRNT-DT-9352',
    title: 'Granite Dining Table with Dining Chair',
    price: 1250,
    wishlist: false,
    cart: false,
    desc: 'A premium granite dining table paired with elegant chairs, perfect for enhancing your dining experience with durability and style.',
    quantity: 1,
    stock: 3,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#2F4F4F', '#FFFFFF'],
    rating: 4.5,
    reviews: 18,
    category: 'furniture',
    tags: ['dining table', 'furniture', 'chairs', 'granite'],
  },
  {
    id: 'e8b9c45f',
    image: ['/product3.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'OUTBR-TBL-7821',
    title: 'Outdoor Bar Table and Stool',
    price: 599,
    wishlist: false,
    cart: false,
    desc: 'A sleek and durable outdoor bar table with matching stools, ideal for patios and garden parties.',
    quantity: 1,
    stock: 7,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#4B5320', '#A9A9A9', '#FFE4C4'],
    rating: 3.8,
    reviews: 8,
    category: 'outdoor furniture',
    tags: ['bar table', 'outdoor', 'stool', 'furniture'],
  },
  {
    id: 'f2c8d73a',
    image: ['/product4.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'PLN-CSL-TEK-6394',
    title: 'Plain Console with Teak Mirror',
    price: 349,
    wishlist: false,
    cart: false,
    desc: 'A minimalist plain console paired with a beautifully crafted teak mirror, perfect for adding elegance to your entryway or living space.',
    quantity: 1,
    stock: 4,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#D2B48C', '#8B4513'],
    rating: 4.2,
    reviews: 10,
    category: 'home decor',
    tags: ['console', 'teak', 'mirror', 'home decor'],
  },
  {
    id: 'a7d4e92f',
    image: ['/product5.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'GRN-CFTBL-4217',
    title: 'Grain Coffee Table',
    price: 225,
    wishlist: false,
    cart: false,
    desc: 'A beautifully crafted grain coffee table with a natural wood finish, perfect for complementing any living room decor.',
    quantity: 1,
    stock: 6,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#A0522D', '#8B4513'],
    rating: 4.0,
    reviews: 15,
    category: 'furniture',
    tags: ['coffee table', 'furniture', 'wooden'],
  },
  {
    id: 'c9e6f47b',
    image: ['/product6.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'KNT-CFTBL-8935',
    title: 'Kent Coffee Table',
    price: 199,
    wishlist: false,
    cart: false,
    desc: 'A sleek and modern Kent coffee table with a durable finish, perfect for enhancing your living space with style.',
    quantity: 1,
    stock: 8,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#708090', '#8B0000'],
    rating: 4.3,
    reviews: 20,
    category: 'furniture',
    tags: ['coffee table', 'furniture', 'modern'],
  },
  {
    id: 'd4a8f67c',
    image: ['/product7.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'RND-CFTBL-CL2-4821',
    title: 'Round Coffee Table_Color 2',
    price: 259,
    wishlist: false,
    cart: false,
    desc: 'A stylish round coffee table with a contemporary design, featuring a durable top and sleek finish.',
    quantity: 1,
    stock: 5,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#696969', '#A52A2A', '#DAA520'],
    rating: 4.1,
    reviews: 13,
    category: 'furniture',
    tags: ['coffee table', 'round', 'furniture'],
  },
  {
    id: 'e1f3b6d9',
    image: ['/product8.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'RCLM-TEK-CFTBL-2641',
    title: 'Reclaimed Teak Coffee Table',
    price: 389,
    wishlist: false,
    cart: false,
    desc: 'A rustic reclaimed teak coffee table that adds a touch of sustainability and vintage charm to any living room.',
    quantity: 1,
    stock: 4,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#8B4513', '#D2B48C'],
    rating: 4.7,
    reviews: 22,
    category: 'furniture',
    tags: ['coffee table', 'reclaimed wood', 'teak', 'furniture'],
  },
  {
    id: 'b8f9a2c7',
    image: ['/product9.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'PLN-CSL-0421',
    title: 'Plain Console_',
    price: 299,
    wishlist: false,
    cart: false,
    desc: 'A minimalist plain console, designed to fit seamlessly into modern interiors while providing a functional storage solution.',
    quantity: 1,
    stock: 6,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#D3D3D3', '#A9A9A9'],
    rating: 4.2,
    reviews: 14,
    category: 'home decor',
    tags: ['console', 'furniture', 'storage'],
  },
  {
    id: 'f2a7d9b5',
    image: ['/product10.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'RCLM-TEK-SB-7254',
    title: 'Reclaimed Teak Sideboard',
    price: 499,
    wishlist: false,
    cart: false,
    desc: 'A spacious reclaimed teak sideboard that offers both rustic charm and practical storage space for any room.',
    quantity: 1,
    stock: 3,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#8B4513', '#DEB887'],
    rating: 4.6,
    reviews: 18,
    category: 'furniture',
    tags: ['sideboard', 'furniture', 'reclaimed wood'],
  },
  {
    id: 'a7c9d1e4',
    image: ['/product11.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'SJP-0825-5512',
    title: 'SJP_0825',
    price: 149,
    wishlist: false,
    cart: false,
    desc: 'A unique and contemporary piece, the SJP_0825 blends modern aesthetics with functional design for any space.',
    quantity: 1,
    stock: 10,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#000000', '#C0C0C0'],
    rating: 3.9,
    reviews: 25,
    category: 'home decor',
    tags: ['modern', 'decor', 'furniture'],
  },
  {
    id: 'd8a3f7b1',
    image: ['/product12.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'BLL-CH-TBL-9834',
    title: 'Bella Chair and Table',
    price: 359,
    wishlist: false,
    cart: false,
    desc: 'A stylish and comfortable Bella chair paired with a matching table, designed to elevate any dining or lounge space.',
    quantity: 1,
    stock: 5,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#6A5ACD', '#FFFFFF'],
    rating: 4.4,
    reviews: 30,
    category: 'furniture',
    tags: ['chair', 'table', 'furniture', 'dining'],
  },
  {
    id: 'c2b4d8a9',
    image: ['/product13.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'GRNT-SQ-SDTBL-3547',
    title: 'Granite Square Side Table',
    price: 299,
    wishlist: false,
    cart: false,
    desc: 'A sleek and durable granite square side table, ideal for modern living rooms or as a chic accent piece in any room.',
    quantity: 1,
    stock: 6,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#808080', '#A9A9A9'],
    rating: 4.5,
    reviews: 22,
    category: 'furniture',
    tags: ['side table', 'furniture', 'granite'],
  },
  {
    id: 'b3e7f0d2',
    image: ['/product14.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'ASGRD-SF-9032',
    title: 'Asgaard Sofa',
    price: 799,
    wishlist: false,
    cart: false,
    desc: 'A luxurious and comfortable Asgaard sofa that combines classic design with modern comfort, perfect for any living room.',
    quantity: 1,
    stock: 4,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#B22222', '#A9A9A9'],
    rating: 4.8,
    reviews: 18,
    category: 'furniture',
    tags: ['sofa', 'furniture', 'living room'],
  },
  {
    id: 'f1d9b2e4',
    image: ['/product15.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'MYA-SF-3S-1578',
    title: 'Maya Sofa Three Seater',
    price: 899,
    wishlist: false,
    cart: false,
    desc: 'The Maya Three Seater Sofa offers spacious comfort and modern style, perfect for large living rooms or lounges.',
    quantity: 1,
    stock: 3,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#FFD700', '#800000'],
    rating: 4.6,
    reviews: 25,
    category: 'furniture',
    tags: ['sofa', 'furniture', 'three seater'],
  },
  {
    id: 'c6e9a7d3',
    image: ['/product16.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'OUT-SF-SET-6821',
    title: 'Outdoor Sofa Set',
    price: 1199,
    wishlist: false,
    cart: false,
    desc: 'A stylish and durable outdoor sofa set designed for comfort and elegance, perfect for your patio, garden, or balcony.',
    quantity: 1,
    stock: 5,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#4682B4', '#F0E68C'],
    rating: 4.7,
    reviews: 30,
    category: 'outdoor furniture',
    tags: ['outdoor sofa', 'furniture', 'patio', 'garden'],
  },
  {
    id: 'b7e3d0f5',
    image: ['/product17.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'ROKT-SS-2358',
    title: 'Rocket Single Seater',
    price: 249,
    wishlist: false,
    cart: false,
    desc: 'A modern and sleek single seater chair designed to provide comfort and style, perfect for any contemporary living space.',
    quantity: 1,
    stock: 8,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#FF6347', '#2F4F4F'],
    rating: 4.3,
    reviews: 18,
    category: 'furniture',
    tags: ['single seater', 'furniture', 'chair'],
  },
  {
    id: 'b6e9d0F5',
    image: ['/product18.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'OUT-SS-2558',
    title: 'side table',
    price: 279,
    wishlist: false,
    cart: false,
    desc: 'A modern and sleek side table designed to provide comfort and style, perfect for any contemporary living space.',
    quantity: 1,
    stock: 8,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#FF6347', '#2F4F4F'],
    rating: 4.3,
    reviews: 43,
    category: 'furniture',
    tags: ['side table', 'furniture', 'table'],
  },
  {
    id: 'b6e9c0F3',
    image: ['/product19.png','/product14.png','/product16.png','/product17.png'],
    SKU: 'INLET-II-2558',
    title: 'modern sofa',
    price: 679,
    wishlist: false,
    cart: false,
    desc: 'A modern and sleek sofa designed to provide comfort and style, perfect for any contemporary living space.',
    quantity: 1,
    stock: 10,
    size:'',
    sizeOptions: ['xl', 'lg', 'sm'],
    color:'',
    colorOptions: ['#FF6347', '#2F4F4F'],
    rating: 4.7,
    reviews: 58,
    category: 'furniture',
    tags: ['sofa', 'furniture', 'chair'],
  },
]
const blogs:blogType[] = [
  {
    id: 'f2b6d8a3',
    title: 'Going All-In with Millennial Design',
    image: '/blogimage1.png',
    desc: 'Explore how millennial design trends are shaping modern spaces with minimalism, functionality, and aesthetic appeal, making every element both practical and beautiful.Lorem ipsum dolor sit amet consectetur adipisicing elit. A neque natus, amet omnis assumenda ea laudantium porro! Aliquam quae perspiciatis, labore, at blanditiis sapiente obcaecati nulla deleniti veniam, consequuntur fugHic quam eius vero officia harum iste, voluptates, consequuntur vel corporis nobis aperiam maiores. Voluptatibus dicta dolore iste quod, repellat exercitationem voluptas nesciunt beatae est quos! Expedita reiciendis tenetur unQuod aspernatur blanditiis sed architecto omnis consequuntur non quos commodi, repellendus illo laboriosam natus! Molestias perspiciatis doloremque, sequi nulla sed commodi vero harum dolorum recusandae vitae, vel nemo aspernatur ullam?',
    date: '09 Dec 2023',
    time: '7mins',
    tag: 'design',
    author: 'Admin',
  },
  {
    id: 'c7e2f1a4',
    title: 'Exploring New Ways of Decorating',
    image: '/blogimage2.png',
    desc: 'Discover innovative techniques and creative ideas to transform your spaces with unique decorations, blending personal style with modern trends for a fresh look.Lorem ipsum dolor sit amet consectetur adipisicing elit. A neque natus, amet omnis assumenda ea laudantium porro! Aliquam quae perspiciatis, labore, at blanditiis sapiente obcaecati nulla deleniti veniam, consequuntur fugit!Hic quam eius vero officia harum iste, voluptates, consequuntur vel corporis nobis aperiam maiores. Voluptatibus dicta dolore iste quod, repellat exercitationem voluptas nesciunt beatae est quos! Expedita reiciendis tenetur unde?Quod aspernatur blanditiis sed architecto omnis consequuntur non quos commodi, repellendus illo laboriosam natus! Molestias perspiciatis doloremque, sequi nulla sed commodi vero harum dolorum recusandae vitae, vel nemo aspernatur ullam?',
    date: '05 Nov 2023',
    time: '6mins',
    tag: 'decorating',
    author: 'Admin',
  },
  {
    id: 'a4d9f3b7',
    title: 'Handmade Pieces That Took Time to Make',
    image: '/blogimage3.png',
    desc: 'Delve into the beauty and craftsmanship of handmade pieces that reflect dedication and artistry, adding a personal and timeless touch to any space.Lorem ipsum dolor sit amet consectetur adipisicing elit. A neque natus, amet omnis assumenda ea laudantium porro! Aliquam quae perspiciatis, labore, at blanditiis sapiente obcaecati nulla deleniti veniam, consequuntur fugit!Hic quam eius vero officia harum iste, voluptates, consequuntur vel corporis nobis aperiam maiores. Voluptatibus dicta dolore iste quod, repellat exercitationem voluptas nesciunt beatae est quos! Expedita reiciendis tenetur unde?Quod aspernatur blanditiis sed architecto omnis consequuntur non quos commodi, repellendus illo laboriosam natus! Molestias perspiciatis doloremque, sequi nulla sed commodi vero harum dolorum recusandae vitae, vel nemo aspernatur ullam?',
    date: '15 Oct 2023',
    time: '8mins',
    tag: 'handmade',
    author: 'Admin',
  },
  {
    id: 'd6e4b2a9',
    title: 'Exploring New Ways of Decorating',
    image: '/blogimage4.png',
    desc: 'Uncover fresh decorating ideas that inspire creativity, combining vibrant colors, textures, and styles to elevate your home’s ambiance and aesthetic.Lorem ipsum dolor sit amet consectetur adipisicing elit. A neque natus, amet omnis assumenda ea laudantium porro! Aliquam quae perspiciatis, labore, at blanditiis sapiente obcaecati nulla deleniti veniam, consequuntur fugit!Hic quam eius vero officia harum iste, voluptates, consequuntur vel corporis nobis aperiam maiores. Voluptatibus dicta dolore iste quod, repellat exercitationem voluptas nesciunt beatae est quos! Expedita reiciendis tenetur unde?Quod aspernatur blanditiis sed architecto omnis consequuntur non quos commodi, repellendus illo laboriosam natus! Molestias perspiciatis doloremque, sequi nulla sed commodi vero harum dolorum recusandae vitae, vel nemo aspernatur ullam?',
    date: '22 Sep 2023',
    time: '5mins',
    tag: 'decorating',
    author: 'Admin',
  },
  {
    id: 'f9a3d7b2',
    title: 'Going All-In with Millennial Design',
    image: '/blogimage5.png',
    desc: 'Dive into the essence of millennial design, embracing clean lines, bold accents, and sustainable elements that redefine modern living spaces.Lorem ipsum dolor sit amet consectetur adipisicing elit. A neque natus, amet omnis assumenda ea laudantium porro! Aliquam quae perspiciatis, labore, at blanditiis sapiente obcaecati nulla deleniti veniam, consequuntur fugHic quam eius vero officia harum iste, voluptates, consequuntur vel corporis nobis aperiam maiores. Voluptatibus dicta dolore iste quod, repellat exercitationem voluptas nesciunt beatae est quos! Expedita reiciendis tenetur unQuod aspernatur blanditiis sed architecto omnis consequuntur non quos commodi, repellendus illo laboriosam natus! Molestias perspiciatis doloremque, sequi nulla sed commodi vero harum dolorum recusandae vitae, vel nemo aspernatur ullam?',
    date: '18 Aug 2023',
    time: '6mins',
    tag: 'design',
    author: 'Admin',
  },
  {
    id: 'e4c7b9f1',
    title: 'Handmade Pieces That Took Time to Make',
    image: '/blogimage6.png',
    desc: 'Celebrate the artistry and effort behind handmade creations, showcasing unique, time-intensive pieces that add character and authenticity to any decor.Lorem ipsum dolor sit amet consectetur adipisicing elit. A neque natus, amet omnis assumenda ea laudantium porro! Aliquam quae perspiciatis, labore, at blanditiis sapiente obcaecati nulla deleniti veniam, consequuntur fugit!Hic quam eius vero officia harum iste, voluptates, consequuntur vel corporis nobis aperiam maiores. Voluptatibus dicta dolore iste quod, repellat exercitationem voluptas nesciunt beatae est quos! Expedita reiciendis tenetur unde?Quod aspernatur blanditiis sed architecto omnis consequuntur non quos commodi, repellendus illo laboriosam natus! Molestias perspiciatis doloremque, sequi nulla sed commodi vero harum dolorum recusandae vitae, vel nemo aspernatur ullam?',
    date: '12 Jul 2023',
    time: '7mins',
    tag: 'handmade',
    author: 'Admin',
  },
  {
    id: 'b3f7a6d9',
    title: 'Modern Home in Milan',
    image: '/blogimage7.png',
    desc: 'Step inside a chic modern home in Milan, where contemporary design meets Italian elegance, blending functionality with timeless aesthetics.Lorem ipsum dolor sit amet consectetur adipisicing elit. A neque natus, amet omnis assumenda ea laudantium porro! Aliquam quae perspiciatis, labore, at blanditiis sapiente obcaecati nulla deleniti veniam, consequuntur fugit!Hic quam eius vero officia harum iste, voluptates, consequuntur vel corporis nobis aperiam maiores. Voluptatibus dicta dolore iste quod, repellat exercitationem voluptas nesciunt beatae est quos! Expedita reiciendis tenetur unde?Quod aspernatur blanditiis sed architecto omnis consequuntur non quos commodi, repellendus illo laboriosam natus! Molestias perspiciatis doloremque, sequi nulla sed commodi vero harum dolorum recusandae vitae, vel nemo aspernatur ullam?',
    date: '03 Jun 2023',
    time: '5mins',
    tag: 'architecture',
    author: 'Admin',
  },
  {
    id: 'c8d2f4a7',
    title: 'Colorful Office Redesign',
    image: '/blogimage8.png',
    desc: 'Explore a vibrant office redesign that integrates bold colors and playful accents, transforming workspaces into inspiring and energizing environments.Lorem ipsum dolor sit amet consectetur adipisicing elit. A neque natus, amet omnis assumenda ea laudantium porro! Aliquam quae perspiciatis, labore, at blanditiis sapiente obcaecati nulla deleniti veniam, consequuntur fugit!Hic quam eius vero officia harum iste, voluptates, consequuntur vel corporis nobis aperiam maiores. Voluptatibus dicta dolore iste quod, repellat exercitationem voluptas nesciunt beatae est quos! Expedita reiciendis tenetur unde?Quod aspernatur blanditiis sed architecto omnis consequuntur non quos commodi, repellendus illo laboriosam natus! Molestias perspiciatis doloremque, sequi nulla sed commodi vero harum dolorum recusandae vitae, vel nemo aspernatur ullam?',
    date: '15 May 2023',
    time: '6mins',
    tag: 'office design',
    author: 'Admin',
  },
]
const Links:Link[] = [
  {
    pathname: 'home',
    pathLink: '/',
  },
  {
    pathname: 'shop',
    pathLink: '/shop',
  },
  {
    pathname: 'blog',
    pathLink: '/blog',
  },
  {
    pathname: 'contact',
    pathLink: '/contact',
  },
]
const Help:Link[] = [
  {
    pathname: 'payment options',
    pathLink: '/payment',
  },
  {
    pathname: 'return',
    pathLink: '/shop/return',
  },
  {
    pathname: 'privacy policy',
    pathLink: '/privacy-policy',
  },
]
const IconLinks:IconLink[] = [
  {
    pathLink: '/user',
    pathname: 'user',
    icon: <User /> ,
  },
  {
    pathLink: '/search',
    pathname: 'search',
    icon: <Search />,
  },
  {
    pathLink: '/wishlist',
    pathname: 'wishlist',
    icon: <Heart />,
  },
  {
    pathLink: '/cart',
    pathname: 'cart',
    icon: <ShoppingCart />,
  },
]
export { Product, blogs, Links, IconLinks, Help }
