import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import Header from "./components/Header";
import Footer from "./components/Footer";
import GlobalContext from './GlobalContext'
import "./globals.css";

const poppins_init=Poppins({
  subsets:['latin'],
  weight:['400','500','700'],
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return (
    <html lang="en">
      <body
        className={`${poppins_init.variable} $ antialiased xs:text-base text-sm flex flex-col min-h-screen max-w-[1440px] relative overflow-x-hidden mx-auto bg-white poppins`}
      >
        <GlobalContext>
          <Header />
          {children}
          <Footer />
        </GlobalContext>
      </body>
    </html>
  );
}
